
# Config
"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $directory\
# $git_branch\
# $git_status\
# $fill\
# $python\
# $rust\
# $golang\
# $nodejs\
# $lua\
# $docker_context\
# $deno\
# $conda\
# $ocaml\
# $php\
# $zig\
# $azure\
# $time\
# $sudo\
# $cmd_duration\
# $line_break\
# $character
# """

format = """
<<<<<<< HEAD
$fill\
=======
>>>>>>> main2
$python\
$rust\
$golang\
$nodejs\
$lua\
$docker_context\
$deno\
$conda\
$ocaml\
$php\
$zig\
$line_break\
$character
"""


[character]
success_symbol = '[Î¶](bold green)'

[fill]
symbol = ' '

[aws]
symbol = "îŒ½  "

[azure]
disabled = false
format = "[$symbol($username)]($style) "
symbol = 'ó° … '
style = 'blue bold'

[buf]
symbol = "ï’ "

[c]
format = '[$symbol($version )]($style)'
symbol = "î˜ "

[conda]
format = '[$symbol($version )]($style)'
symbol = "ï„Œ "

[crystal]
format = '[$symbol($version )]($style)'
symbol = "î˜¯ "

[dart]
format = '[$symbol($version )]($style)'
symbol = "î˜ "

[directory]
read_only = " ó°Œ¾"
truncation_length = 5
truncate_to_repo = true
truncation_symbol = '../'

[docker_context]
symbol = "ïŒˆ "

[elixir]
format = '[$symbol($version )]($style)'
symbol = "î˜­ "

[elm]
format = '[$symbol($version )]($style)'
symbol = "î˜¬ "

[fennel]
format = '[$symbol($version )]($style)'
symbol = "îš¯ "

[fossil_branch]
symbol = "ï˜ "

[git_branch]
symbol = "ï˜ "

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'


[golang]
format = '[$symbol($version )]($style)'
symbol = "ğŸğŸ’¨"

[gcloud]
symbol = 'ğŸ‡¬ï¸ '
disabled = false
format = '[$symbol$active]($style) '

[gcloud.project_aliases]
very-long-project-name = 'vlpn'

[guix_shell]
format = '[$symbol($version )]($style)'
symbol = "ïŒ¥ "

[haskell]
format = '[$symbol($version )]($style)'
symbol = "î· "

[haxe]
symbol = "î™¦ "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_only = true
ssh_symbol = "î¬ "
format = '[$ssh_symbol](bold blue) [$hostname](bold green) '
disabled = false

[java]
format = '[$symbol($version )]($style)'
symbol = "î‰– "

[julia]
format = '[$symbol($version )]($style)'
symbol = "î˜¤ "

[kotlin]
format = '[$symbol($version )]($style)'
symbol = "î˜´ "

[lua]
format = '[$symbol($version )]($style)'
symbol = "ğŸŒ™ "

[memory_usage]
symbol = "ó°› "

[meson]
format = '[$symbol($version )]($style)'
symbol = "ó°”· "

[nim]
format = '[$symbol($version )]($style)'
symbol = "ó°†¥ "

[nix_shell]
format = '[$symbol($version )]($style)'
symbol = "ïŒ“ "

[nodejs]
format = '[$symbol($version )]($style)'
symbol = "îœ˜ "

[ocaml]
format = '[$symbol($version )]($style)'
symbol = "î™º "

[os]
disabled = false

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
symbol = "ó°— "

[perl]
format = '[$symbol($version )]($style)'
symbol = "î™¾ "

[php]
format = '[$symbol($version )]($style)'
symbol = "î˜ˆ "

[pijul_channel]
symbol = "ï˜ "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "îˆµ "
pyenv_version_name = false

[rlang]
format = '[$symbol($version )]($style)'
symbol = "ó°Ÿ” "

[ruby]
format = '[$symbol($version )]($style)'
symbol = "î‘ "

[rust]
format = '[$symbol($version )]($style)'
symbol = "î¨ "

[scala]
format = '[$symbol($version )]($style)'
symbol = "îœ· "

[sudo]
style = 'bold green'
symbol = 'sudo '
disabled = false

[swift]
format = '[$symbol($version )]($style)'
symbol = "î• "

[time]
disabled = false
format = '$time '
time_format = 'ğŸ“… wk %W %d-%m ğŸ•˜ %R'

[zig]
format = '[$symbol($version )]($style)'
symbol = "îš© "
